-- Create the item table used by the example item endpoints.
-- The id is a UUIDv7 generated by the service, so it is a CHAR(36) rather than
-- an auto-increment column. DATETIME(6) keeps microsecond precision, which the
-- list ordering relies on to separate rows created in the same second.
CREATE TABLE IF NOT EXISTS item (
    id         CHAR(36)     NOT NULL,
    name       VARCHAR(128) NOT NULL,
    quantity   INT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(6)  NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_item_name (name),
    KEY idx_item_created_at (created_at, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
