#!/usr/bin/env bash
#
# Generate a README.md for every package under pkg/ from its source.
#
# The package doc comment supplies the prose, the first runnable Example
# supplies the code sample, and "go list" supplies the dependency footprint.
# Nothing in a generated README is authored there: edit the Go source instead.

set -euo pipefail

MODULE="github.com/tecnickcom/nurago"

# Byte ordering for every sort: the output must not depend on the locale.
unset LC_ALL
export LC_COLLATE=C

for dir in $(go list -f '{{.Dir}}' ./pkg/... | sed "s|^$PWD/||" | sort); do
	name="${dir##*/}"
	imp="$MODULE/$dir"
	src="$dir/$name.go"
	example=$(ls "$dir"/example_*_test.go 2>/dev/null | head -1)
	mods=$(go list -deps -f '{{if .Module}}{{.Module.Path}}{{end}}' "$imp" |
		{ grep -v "^$MODULE" || true; } | sort -u)
	count=$(printf '%s' "$mods" | { grep -c . || true; })

	{
		echo "<!-- Generated by resources/gendoc/gendoc.sh from $name.go. Do not edit. -->"
		echo
		echo "# $name"
		echo
		echo "[![Go Reference](https://pkg.go.dev/badge/$imp.svg)](https://pkg.go.dev/$imp)"
		echo

		# The doc comment is already Go's markdown-like syntax. Only doc links
		# need converting: [Name] has no markdown meaning, so render it as code.
		sed -n '/^\/\*/,/^\*\//p' "$src" | sed '1d;$d' |
			sed -E "s|\[$MODULE/pkg/([a-z0-9/]+)\]|[\1](https://pkg.go.dev/${MODULE}/pkg/\1)|g" |
			sed -E 's/\[([A-Za-z0-9_.\/]+)\]([^(:]|$)/`\1`\2/g' |
			sed -E 's/^# /## /' |
			sed '/^\[[^]]*\]: /d'

		echo
		echo '## Example'
		echo
		echo '```go'
		awk '/^func Example/{f=1;next} f&&/^}$/{exit} f' "$example" | sed 's/^\t//'
		echo '```'
		echo
		echo "Full source is in [$(basename "$example")]($(basename "$example"))."
		echo "More runnable examples are on [pkg.go.dev](https://pkg.go.dev/$imp#pkg-examples)."
		echo
		echo '## Dependencies'
		echo
		if [ "$count" -eq 0 ]; then
			echo "This package reaches no external module: it uses only the Go standard library."
		else
			if [ "$count" -eq 1 ]; then
				noun="module"
			else
				noun="modules"
			fi
			echo "Importing this package pulls $count external $noun:"
			echo
			printf '%s\n' "$mods" | sed 's/^/- `/;s/$/`/'
		fi
		echo
		echo '## Links'
		echo
		echo "- [Reference documentation](https://pkg.go.dev/$imp)"
		echo "- [All nurago packages]($(echo "$dir" | sed 's|[^/]*|..|g')/README.md)"
	} >"$dir/README.md"
done

# Root README: the headline dependency figure, between generated markers.
zero=$(for d in $(go list ./pkg/...); do
	n=$(go list -deps -f '{{if .Module}}{{.Module.Path}}{{end}}' "$d" |
		{ grep -v "^$MODULE" || true; } | sort -u | { grep -c . || true; })
	[ "$n" -eq 0 ] && echo "\`${d##*/}\`" || true
done | sort | paste -sd, - | sed 's/,/, /g')

total=$(go list ./pkg/... | wc -l)
zcount=$(printf '%s' "$zero" | tr ',' '\n' | { grep -c . || true; })

{
	echo "<!-- gendoc:deps:start -->"
	echo
	echo "**$zcount of the $total packages reach no external module at all**, using nothing"
	echo "beyond the Go standard library:"
	echo
	printf '%s.\n' "$zero" | fold -s -w 78 | sed 's/ *$//'
	echo
	echo "Each package README lists its own footprint. Verify any of them with:"
	echo
	echo '```bash'
	echo "go list -deps -f '{{if .Module}}{{.Module.Path}}{{end}}' \\"
	echo "  $MODULE/pkg/backoff | sort -u"
	echo '```'
	echo
	echo "<!-- gendoc:deps:end -->"
} >/tmp/gendoc-deps.$$

awk -v f=/tmp/gendoc-deps.$$ '
	/<!-- gendoc:deps:start -->/ {while ((getline l < f) > 0) print l; skip=1; next}
	/<!-- gendoc:deps:end -->/ {skip=0; next}
	!skip
' README.md >README.md.new && mv README.md.new README.md
rm -f /tmp/gendoc-deps.$$

# Root README: the package catalog, between generated markers.
{
	echo "<!-- gendoc:catalog:start -->"
	echo
	echo "All $total packages, each linking to its own README. The description is the"
	echo "first sentence of the package documentation."
	echo
	for d in $(go list ./pkg/... | sort); do
		rel="pkg/${d#$MODULE/pkg/}"
		echo "- [${d##*/}]($rel) - $(go doc "$d" | sed -n '3,20p' |
			awk 'BEGIN{RS=""} NR==1' | tr '\n' ' ' | sed 's/  */ /g;s/ $//' |
			sed -E 's/\[([^]]+)\]/\1/g' | sed -E "s/^Package ${d##*/} //")"
	done
	echo
	echo "<!-- gendoc:catalog:end -->"
} >/tmp/gendoc-cat.$$

awk -v f=/tmp/gendoc-cat.$$ '
	/<!-- gendoc:catalog:start -->/ {while ((getline l < f) > 0) print l; skip=1; next}
	/<!-- gendoc:catalog:end -->/ {skip=0; next}
	!skip
' README.md >README.md.new && mv README.md.new README.md
rm -f /tmp/gendoc-cat.$$

# llms.txt: a flat index of every package synopsis.
{
	echo "# nurago"
	echo
	echo "> $total independent Go packages for backend services. Each is imported on its"
	echo "> own and pulls only its own dependencies; $zcount reach no external module at all."
	echo
	echo "Install: \`go get $MODULE\`"
	echo "Reference documentation: https://pkg.go.dev/$MODULE"
	echo
	echo "## Packages"
	echo
	for d in $(go list ./pkg/... | sort); do
		echo "- [${d##*/}](https://pkg.go.dev/$d): $(go doc "$d" | sed -n '3,20p' |
			awk 'BEGIN{RS=""} NR==1' | tr '\n' ' ' | sed 's/  */ /g;s/ $//' |
			sed -E 's/\[([^]]+)\]/\1/g')"
	done
} >llms.txt

echo "generated $(find pkg -name README.md | wc -l) package READMEs, README.md deps + catalog, llms.txt"
